version: '3.7'

services:
  webdb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword12345
      MYSQL_DATABASE: VERA_Shooter_Localization
      MYSQL_USER: vera
      MYSQL_PASSWORD: mysqlpassword
    ports: 
      - "3306:3306"
    volumes:
      - ./web_interface/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
  webserver:
    image: yiisoftware/yii2-php:7.3-apache
    volumes:
      - source: ./web_interface
        target: /app/web
        type: bind
    ports:
      - "8080:80"
  python_backend:
    image: vera:1.0.0
    ports:
      - "21320:21320"
    


    




